### ISSUE TITLE
Cannot read property 'eth_getBlockByNumber' of undefined

### ISSUE THREAD

**Issue by meowsbits** [etclabscore/stargate-sg1#1]
```
ubp52 ~/dev/meowsbits/stargate-sg1 master
$ npm run start

> @etclabscore/pristine-typescript@1.0.0 start /home/ia/dev/meowsbits/stargate-sg1
> npm run build && node build/index.js

npm WARN npm npm does not support Node.js v13.0.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/

> @etclabscore/pristine-typescript@1.0.0 build /home/ia/dev/meowsbits/stargate-sg1
> tsc

Installing multi-geth v1.9.2
multi-geth 1.9.2 installed ok? true
Setting up client: goerli
Setting up client: kotti
Exec finished without errors
/home/ia/dev/meowsbits/stargate-sg1/build/star.js:85
        this.erpc.eth_getBlockByNumber("latest", true)
                  ^

TypeError: Cannot read property 'eth_getBlockByNumber' of undefined
    at Timeout.StarClass.setStateFromClient [as _onTimeout] (/home/ia/dev/meowsbits/stargate-sg1/build/star.js:85:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @etclabscore/pristine-typescript@1.0.0 start: `npm run build && node build/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @etclabscore/pristine-typescript@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ia/.npm/_logs/2019-10-28T15_19_49_654Z-debug.log
```

**Comment by meowsbits** [comment]
Coming from here, I think: https://github.com/etclabscore/stargate-sg1/blob/master/src/star.ts#L41

**Comment by meowsbits** [comment]
Fixed via https://github.com/etclabscore/stargate-sg1/commit/c6e91a37f02a0c1cb387f5f6be80ac2c236da212
